config-openwrt-ar71xx-ap83: Remove package "curl" since I failed to resolve the compiling errors:
In file included from file.c:52:0:
urldata.h:304:3: error: unknown type name 'x509_crt'
urldata.h:305:3: error: unknown type name 'x509_crt'
make[5]: *** [libcurl_la-file.lo] Error 1